[package]
name = "nyaodle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.3"
log = "0.4.21"
poise = "0.6.1"
tokio = { version = "1.36.0", features = ["full"] }
